### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by brucou** [m64253/node-convert#1]
Hi @m64253 Mikael,

I was wondering if you coud free the package name convert so I can use for an open source project I am working on. In the README.md you mention `node-convert` but in the package.json the name is set to `convert` so I can't use it. It would be great to do that if you no longer has a use of that package. 

Per npm rules, you can [unpublish a package](https://www.npmjs.com/policies/unpublish) under certain conditions;
- no dependent
- less than 300 downloads in the last week
- you are the lone contributor to it

All these conditions seems to apply, in which case, `npm unpublish <package_name> --force.` should do the trick.  Let me know if that is ok with you. I would be enormously grateful if you would not mind unpublish your package (you can always republish it under node-convert name). 

In any case, thank you for reeading up till now,
Kind regards,

**Comment by jonahsnider** [comment]
I was *also* hoping to yoink the package name convert for my totally typesafe [unit conversion library](https://github.com/pizzafox/convert) I made.

What's the move?
